services:
  android:
    image: redroid/redroid@sha256:68ae34dfbdb1000687d89691f12b9e17daa1b5c3ce528ada7e9d007090daab86
    container_name: android-runtime
    hostname: android-runtime
    privileged: true
    restart: unless-stopped
    cpus: 5.0
    cpu_shares: 2048
    mem_limit: 6g
    mem_reservation: 4g
    shm_size: 1g
    pids_limit: 4096
    ports:
      - "127.0.0.1:5556:5555"
    volumes:
      - ../data/android:/data
    command:
      - androidboot.use_memfd=1
      - androidboot.redroid_gpu_mode=guest
      - androidboot.redroid_width=720
      - androidboot.redroid_height=1280
      - androidboot.redroid_dpi=320
      - androidboot.redroid_fps=45
    networks:
      - android-personal

  proxy:
    image: caddy@sha256:98eb57d882ccd5213d1688764db10c1ca2c58a1ca3a6717a3411ad798f7a423a
    container_name: android-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../data/caddy/data:/data
      - ../data/caddy/config:/config

networks:
  android-personal:
    name: android-personal
    external: true
